# Informe

## Preparación

Los informes de laboratorio se elaborarán y enviarán a la persona docente en un documento de Word. Se redactan en pasado y en forma impersonal. El informe debe estar escrito con letra tipo Arial, tamaño 12 y a doble columna. El tamaño de letra puede variar dependiendo de la sección (cuadros, formulas, etc.). Se recomienda seguir el siguiente [formato](https://unaaccr-my.sharepoint.com/:w:/g/personal/leonardo_mena_rivera_una_ac_cr/EUaJiEvk3M5DvDyo20zztLQB3LY8lCpcUevc80gAUE6v3Q). Los informes deberán entregarse en el Aula Virtual o OneNote según las fechas indicadas en el cronograma del curso.

El informe debe incluir lo siguiente:

1.  Encabezado: cada página deberá estar numerada en la parte superior con el siguiente consecutivo: **UNA-EQ-LQAC-NNNNN-IIII-RL-PP-DD**, donde NNNNN será sustituido por el NRC del curso, IIII será sustituido por las iniciales del o de la estudiante, PP será sustituido por el código de la práctica (por ejemplo, P1 o P2), DD será sustituido por el número de página del documento y RL significa reporte de laboratorio.

2.  Título de la práctica

3.  Datos generales: nombre de la persona estudiante, fecha de realización de la práctica, fecha de entrega del informe y nombre del profesor de laboratorio.

4.  Fundamento teórico: debe incluirse la versión corregida del fundamento teórico presentado en el cuaderno de laboratorio.

5.  Materiales y métodos: incluye una descripción del procedimiento experimental realizado.

6.  Resultados y discusión: debe presentar un aporte propio de ideas teórico - prácticas, a raíz de la experiencia vivida en el laboratorio. En primera instancia debe reportar el resultado(s) obtenido(os) en la práctica incluyendo el promedio, incertidumbre expandida y desviación estándar relativa en porcentaje. En lo referente a la discusión de la práctica, debe discutirse y analizar los resultados obtenidos. Entre otras cosas, puede considerar:

    a.  Interpretar el resultado en el contexto de la reglamentación (nacional o internacional), valores de referencia, valores recomendados, artículos científicos u otros recursos.
    b.  Presentar fuentes de error justificando cuando es posible, las diferencias obtenidas en los resultados. Este punto no debe ser la excusa para justificar en cada informe todas las posibles equivocaciones cometidas.
    c.  Dar recomendaciones para disminuir fuentes de error.
    d.  Presentar otros métodos de análisis para el analito y compararlo con el que se realizó.

    *Debe evitarse presentar una copia textual de páginas de otros textos, insertados y con elementos repetitivos. Debe citar referencias bibliográficas relevantes cuando sea pertinente.*

    **Ejemplo de discusión**: La literatura relacionada con la química analítica muestra una gran cantidad de métodos gravimétricos, volumétricos e instrumentales para analizar mercurio *(1)*. Dicho elemento se puede analizar también mediante la técnica combinada de extracción con posterior determinación espectrofotométrica. El mercurio y un agente ligante forman complejos solubles en la fase orgánica que posteriormente son determinados por espectrofotometría ultravioleta-visible *(2,4)*. ...

7.  Referencias: en la discusión de resultados debe indicarse con un número entre paréntesis, en cursiva y al final de la frase, la correspondiente referencia bibliográfica consultada. Las referencias deben presentarse ordenadas numéricamente con forme se citan en la discusión, como en el párrafo anterior. Se debe incluir un mínimo de tres referencias bibliográficas de libros de texto o artículos científicos. Puede usar referencias de internet, pero después de haber completado las tres citas de libros o revistas. Para citar las referencias bibliográficas se seguirá el formato de la American Chemical Society (ACS) [@ACSguide]. Algunos ejemplos se pueden consultar en el siguiente [enlace](https://pubs.acs.org/doi/full/10.1021/acsguide.40303). Se recomienda el uso de software especializado como [Zootero](https://www.zotero.org/) o [Mendeley](https://www.mendeley.com/).

## Evaluación

La evaluación del informe de laboratorio contempla los siguientes aspectos:

+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| Rubro                  | Aspectos a calificar                                                                                                                                                                                                                                                                                                                                                                                                                                            | \%   |
+========================+=================================================================================================================================================================================================================================================================================================================================================================================================================================================================+======+
| Introducción           | Presenta el fundamento de la técnica de forma correcta e incorpora las correcciones efectuadas por la persona docente.                                                                                                                                                                                                                                                                                                                                          | 15   |
+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| Métodos                | Presenta un breve resumen del procedimiento experimental redactado en prosa y en pasado.                                                                                                                                                                                                                                                                                                                                                                        | 20   |
+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| Resultados y discusión | Presenta un aporte propio de ideas teórico-prácticas, las cuales se encuentran relacionadas con los resultados obtenidos en la práctica y con la experiencia vivida en el laboratorio.                                                                                                                                                                                                                                                                          | 50   |
|                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |      |
|                        | Reporta el resultado(s) obtenidos en la práctica incluyendo el promedio, incertidumbre expandida y desviación estándar relativa en porcentaje.                                                                                                                                                                                                                                                                                                                  |      |
|                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |      |
|                        | Incluye gráficos y figuras si es necesario.                                                                                                                                                                                                                                                                                                                                                                                                                     |      |
|                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |      |
|                        | Incluye en la discusión: a) interpretación del resultado en el contexto de la reglamentación (nacional o internacional), valores de referencia, valores recomendados, artículos científicos u otros recursos, b) fuentes de error justificando, cuando es posible, las diferencias obtenidas en los resultados, c) recomendaciones para disminuir fuentes de error; y d) presenta otros métodos de análisis para el analito y lo compara con el que se utilizó. |      |
+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| Referencias            | Incluye al menos tres referencias bibliográficas (excluyendo los libros de texto de laboratorio y teoría).                                                                                                                                                                                                                                                                                                                                                      | 15   |
|                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |      |
|                        | Utiliza el formato de la ACS.                                                                                                                                                                                                                                                                                                                                                                                                                                   |      |
+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+

Cada rubro se califica utilizando una escala de *excelente* (4p), *satisfactorio* (3p), *regular* (2p), *insatisfactorio* (1p) o *deficiente* (0p). La calificación se realiza basado en el grado de cumplimiento según lo solicitado, *excelente* (100%), *satisfactorio* (85-100%), *regular* (50-85%), *insatisfactorio* (\<50%) y *deficiente* (no presenta la sección).

## Referencias
