project:
  type: book

book:
  title: "Instructivo de laboratorio"
  author: "L Mena Rivera"
  date: "2/26/2023"
  chapters:
    - index.qmd
    - part: Generalidades
      chapters:
        - generalidades.qmd
        - cuaderno.qmd
        - informe.qmd
    - part: Experimentos
      chapters:
        - recursos.qmd
    - part: Incertidumbres
      chapters: 
        - incertidumbres.qmd

bibliography: references.bib
csl: american-chemical-society.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport

editor: visual