project:
  type: book

book:
  title: "Instructivo de laboratorio"
  author: "L Mena Rivera"
  reader-mode: true
  repo-url: https://github.com/leomenar/Instructivo_Lab_QA.git
  date: "2/26/2023"
  chapters:
    - index.qmd
    - part: Generalidades
      chapters:
        - generalidades/generalidades.qmd
        - generalidades/cuaderno.qmd
        - generalidades/informe.qmd
    - part: Experimentos
      chapters:
        - recursos/recursos.qmd
    - part: Incertidumbres
      chapters: 
        - incertidumbres/incertidumbres.qmd
        - incertidumbres/NaOH.qmd
        - incertidumbres/sulfatos.qmd

bibliography: references.bib
csl: american-chemical-society.csl

format:
  html:
    theme: litera
  pdf:
    documentclass: scrreport

editor: visual